### ISSUE TITLE
Session locking

### ISSUE THREAD

**Issue by SamMousa** [hoaproject/Eventsource#18]
Somewhere inside this library some session locking seems to be occuring. Test script:
````
<?php
include __DIR__ . '/../protected/vendor/autoload.php';
ob_end_flush();
$server = new \Hoa\Eventsource\Server();
$i = 0;

while($i < 20) {
    $i++;
    $server->send(time(), $i);
    sleep(1);
}
````

This code should send 20 messages over 20 seconds. When calling this from a server in 2 browser tabs, 1 stays empty until all 20 messages have appeared in the other, after which it starts displaying messages.
If I instead open 1 tab in private browsing mode both tabs show the messages simultaneously.

**Comment by SamMousa** [comment]
Hmm, it could be some PHP session handling instead of user code since when I removed cookies this seems to no longer occur...

**Comment by Hywan** [comment]
Hi :-),

It is also possible that your HTTP server has a buffer. We are [doing everything to avoid this](https://github.com/hoaproject/Eventsource/blob/e607b4ec00954a64c90205d14ef761574864c93a/Server.php#L122-L125) but we do not support all HTTP servers.

Glad your issue is fixed!
